### PR TITLE
lumen test pull

### PR DESCRIPTION
**Pull request by bituka**
Hi Kevs, 

Sumakit ulo ko... Hehehe! Please try if this will work.

### CODE REVIEW

**Comment by lightshire** [comment]
I have an issue with your /public folder. 

Please .gitignore the required components and use bower components to be able to re-pull it all later.

It'll be much more better if you'll do that. Maslalo na sa dependencies.

**Comment by rmrhz** [comment]
This needs bower.

**Comment by bituka** [comment]
Sorry ano po yung bower?

**Comment by bituka** [comment]
Hello sir gian,

Will .gitnore the dependencies.

Ano po issue sa /public folder?

**Comment by lightshire** [comment]
@bituka 

google bro.

**Comment by bituka** [comment]
Haha. Uu nga nakita ko na. :) is it really required?

**Comment by lightshire** [comment]
do you really want people to collaborate properly?

Kasi if so, yes its required.

**Comment by bituka** [comment]
Alright. Will do then.

**Comment by bituka** [comment]
Hello Sir Gian. Please check if what I did is correct or anything is
missing. I have requested for another pull.

**Pull request closed without merging**
